# Generated by Django 5.2 on 2025-05-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
