# Generated by Django 5.2.1 on 2025-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employees_contact_alter_employees_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Sales', 'Sales'), ('Finance', 'Finance')], max_length=100)),
                ('role', models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('HR Manager', 'HR Manager'), ('Sales Executive', 'Sales Executive'), ('Accountant', 'Accountant')], max_length=100)),
                ('join_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
